<!DOCTYPE html>
<html>

<head>
    <title>{{ $resep->nama }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 30px;
            color: #333;
        }

        h1,
        h2,
        h3 {
            text-align: center;
            margin-bottom: 10px;
        }

        h1 {
            font-size: 28px;
            color: #04d434;
        }

        h2 {
            font-size: 22px;
            color: #04d434;
        }

        h3 {
            font-size: 18px;
            border-bottom: 2px solid #04d434;
            padding-bottom: 5px;
        }

        .recipe-header {
            text-align: center;
            margin-bottom: 20px;
        }

        .recipe-header img {
            width: 100%;
            max-height: 300px;
            object-fit: cover;
            border-radius: 10px;
            margin-bottom: 15px;
        }

        .info {
            text-align: center;
            margin-bottom: 20px;
            font-size: 14px;
            color: #555;
        }

        .section {
            margin-bottom: 25px;
        }

        .ingredients ul,
        .steps ol {
            margin-left: 20px;
        }

        .ingredients li,
        .steps li {
            margin-bottom: 5px;
        }

        .footer {
            text-align: center;
            font-size: 12px;
            color: #aaa;
            margin-top: 50px;
        }
    </style>
</head>

<body>

    <div class="recipe-header">
        <h1>{{ $resep->nama }}</h1>
        @if (isset($resep->gambar[0]))
            <img src="{{ storage_path('app/public/' . $resep->gambar[0]) }}" alt="{{ $resep->nama }}">
        @endif
    </div>

    <div class="info">
        <span><strong>Prep:</strong> {{ $resep->persiapan }} mins</span> |
        <span><strong>Cook:</strong> {{ $resep->masak }} mins</span> |
        <span><strong>Yields:</strong> {{ $resep->hasil }} servings</span>
    </div>

    <div class="section">
        <h3>Description</h3>
        <p>{{ $resep->des }}</p>
    </div>

    <div class="section ingredients">
        <h3>Ingredients</h3>
        <ul>
            @foreach (json_decode($resep->bahan, true) as $bahan)
                <li>{{ $bahan }}</li>
            @endforeach
        </ul>
    </div>

    <div class="section steps">
        <h3>Steps</h3>
        <ol>
            @foreach (json_decode($resep->langkah, true) as $langkah)
                <li>{{ $langkah }}</li>
            @endforeach
        </ol>
    </div>

    <div class="footer">
        Generated by My Recipes App - {{ date('F d, Y') }}
    </div>

</body>

</html>
